app1/urls.py
from django.urls import path
from app1 import views
app_name='app1'

urlpatterns = [
    path('',views.index,name='index'),
    path('base/',views.base,name='base'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')

]

pro1/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls'))
]
if settings.DEBUG:
    urlpatterns += static (settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app1/models.py
from django.db import models

# Create your models here.
class Movies(models.Model):
    img = models.ImageField(upload_to='pics')
    name=models.CharField(max_length=50)
    desc=models.TextField()
    year=models.IntegerField()

    def __str__(self):
        return self.name

app1/forms.py
from django import forms
from .models import Movies
class MoviesForm(forms.ModelForm):
    class Meta:
        model=Movies
        fields=['name','desc','year','img']

app1/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from app1.models import Movies
from . forms import MoviesForm

def base(request):
    return render(request,'base.html')

def index(request):
    movie=Movies.objects.all()
    context={
       'movie_list':movie
    }
    return render(request,'index.html',context)

def detail(request,movie_id):
    movie=Movies.objects.get(id=movie_id)
    return render(request,'detail.html',{'movie':movie})

def add_movie(request):
    if request.method=='POST':
        img=request.FILES['img']
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        movie=Movies(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,'add_movie.html')

def update(request,id):
    movie=Movies.objects.get(id=id)
    form=MoviesForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movies.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

templates/add_movie.html
{% extends 'base.html' %}
{% block body %}
<center>
  <h2>Add Movie here...</h2><br>
<form method="post" enctype="multipart/form-data">
{% csrf_token %}

  <input type="text" name="name" placeholder="Enter movie name"><br><br><br>

  <input type="text" name="desc" placeholder="Enter description"><br><br><br>

  <input type="text" name="year" placeholder="Enter year"><br><br><br>
  Movie Image
  <input type="file" name="img"><br><br><br>
  <input type="submit" value="Add Movie">
</form></center>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">

    Online Movie Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="post">
  {% csrf_token %}
  Are you want to delete this movie?
  <input type="submit" value="Yes">
</form>
{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <img src="{{ movie.img.url }}" alt="{{ movie.name }}" width="600" height="500">
      </div>
      <div class="col-md-5">
        <center><h2 style="font-weight:bold;">{{ movie.name }}</h2></center>
        <h4>{{ movie.desc }}</h4>
        <p>Released: {{ movie.year }}</p>
          <center>
        <a class="btn btn-warning" href="{% url 'app1:update' movie.id %}">Edit</a>
        <a class="btn btn-danger" href="{% url 'app1:delete' movie.id %}">Delete</a>
              </center>
      </div>
    </div>
  </div>
{% endblock %}

templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Update">
</form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static  %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-4">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="{{ i.img.url }}" alt="Card image cap" height="150px;">
                <div class="card-body">
                    <center><h4 class="card-title">{{ i.name }}</h4></center>
                    <p class="card-text">{{ i.desc }}</p>
                    <center><a href="{% url 'app1:detail' i.id %}" class="btn btn-danger">Explore More</a></center>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>



{% endblock %}




<!--adminl kodthad index pagel show cheyyan-->
<!--{% for i in movie_list %}-->

<!--<h2>{{ i.id }}.{{ i.name }}</h2>-->
<!--<h4><p>{{ i.desc }}</p></h4>-->
<!--<h4>Released :{{ i.year }}</h4>-->
<!--<br>-->
<!--{% endfor %}-->